"""
Frank Ocean Song Library
Each song has a valence score (0.0 = sad/dark, 1.0 = happy/bright)
Valence scores are manually assigned based on musical and lyrical analysis
"""

FRANK_LIBRARY = [
    # Blonde (2016)
    {"title": "Nikes", "id": "3wb2wm3GAZf8hLIFm5s0mZ", "album": "Blonde", "valence": 0.15, 
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Ivy", "id": "2ZWlPOoWh0626oTaHrnl2a", "album": "Blonde", "valence": 0.35,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Pink + White", "id": "3xKsf9qdS1CyvXSMEid6g8", "album": "Blonde", "valence": 0.65,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Solo", "id": "19YKaevk2mNQpuyuHJmYpk", "album": "Blonde", "valence": 0.28,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Skyline To", "id": "4OMJGnvZfDvsePyCwRGO7X", "album": "Blonde", "valence": 0.40,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Self Control", "id": "2LMkwUfqC6S6s6qDVlEuzV", "album": "Blonde", "valence": 0.22,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Nights", "id": "7eqoqGkKe8EK7BDw8Kpv6P", "album": "Blonde", "valence": 0.45,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Solo (Reprise)", "id": "3JLwtnT1ng4Erz6jQJBJcn", "album": "Blonde", "valence": 0.30,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Pretty Sweet", "id": "3pZfMvAr0SUpXqPK7CgRNt", "album": "Blonde", "valence": 0.38,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "White Ferrari", "id": "2LMkwUfqC6S6s6qDVlEuzV", "album": "Blonde", "valence": 0.18,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Seigfried", "id": "6Nle9hKrkL1wQpwNfEkxjh", "album": "Blonde", "valence": 0.12,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Godspeed", "id": "7DFLUkBRMlKHvY2FvnLmS2", "album": "Blonde", "valence": 0.32,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},
    {"title": "Futura Free", "id": "3bn7hJLn74RKdL2kF8oLBk", "album": "Blonde", "valence": 0.35,
     "cover": "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg"},

    # Channel Orange (2012)
    {"title": "Thinkin Bout You", "id": "7DfFc7a6Rwfi3YQMRbDMau", "album": "Channel Orange", "valence": 0.48,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},
    {"title": "Sweet Life", "id": "0Iv9E0h2ObYSoTJEhzVl30", "album": "Channel Orange", "valence": 0.72,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},
    {"title": "Super Rich Kids", "id": "6IHxDGwmOIcpuQO60FY3DA", "album": "Channel Orange", "valence": 0.55,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},
    {"title": "Pilot Jones", "id": "27O8lPvJtqMYjWPFbfSiwq", "album": "Channel Orange", "valence": 0.38,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},
    {"title": "Crack Rock", "id": "4WlLdFVWfs9FH7VXdNCLYl", "album": "Channel Orange", "valence": 0.20,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},
    {"title": "Pyramids", "id": "4ANwUJCHeOlJBEGSsHmF4U", "album": "Channel Orange", "valence": 0.58,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},
    {"title": "Lost", "id": "5gcCHnCWQqFiPjMjUlFQaw", "album": "Channel Orange", "valence": 0.68,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},
    {"title": "Monks", "id": "5ZVBRTV0YfuUFELMdMONnl", "album": "Channel Orange", "valence": 0.45,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},
    {"title": "Bad Religion", "id": "3sFHHFk9reUMgBaFJVaaXU", "album": "Channel Orange", "valence": 0.08,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},
    {"title": "Pink Matter", "id": "5HNCy40Ni5BZJFw1TKzRsC", "album": "Channel Orange", "valence": 0.42,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},
    {"title": "Forrest Gump", "id": "5BMvN8dq9VLU2HUgRwGJxB", "album": "Channel Orange", "valence": 0.75,
     "cover": "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg"},

    # Nostalgia, Ultra (2011)
    {"title": "Novacane", "id": "2qm3EQFmuLbz8IkXN8mI4p", "album": "Nostalgia, Ultra", "valence": 0.62,
     "cover": "https://upload.wikimedia.org/wikipedia/en/e/e7/Nostalgia_ultra_cover.jpg"},
    {"title": "Swim Good", "id": "3aOq5jZFLiGhnKLrPTyLqv", "album": "Nostalgia, Ultra", "valence": 0.35,
     "cover": "https://upload.wikimedia.org/wikipedia/en/e/e7/Nostalgia_ultra_cover.jpg"},
    {"title": "Songs for Women", "id": "38wpNKPZjkFWFSYOGGDON2", "album": "Nostalgia, Ultra", "valence": 0.52,
     "cover": "https://upload.wikimedia.org/wikipedia/en/e/e7/Nostalgia_ultra_cover.jpg"},
    {"title": "There Will Be Tears", "id": "3yPJWKB0MQS7xqbFGwEtLl", "album": "Nostalgia, Ultra", "valence": 0.18,
     "cover": "https://upload.wikimedia.org/wikipedia/en/e/e7/Nostalgia_ultra_cover.jpg"},
    {"title": "Strawberry Swing", "id": "2JxgaHjHfN0gCi3MdnxMmu", "album": "Nostalgia, Ultra", "valence": 0.70,
     "cover": "https://upload.wikimedia.org/wikipedia/en/e/e7/Nostalgia_ultra_cover.jpg"},

    # Singles
    {"title": "Chanel", "id": "6Nv3ATD0EVKA0GoTZFscB4", "album": "Single", "valence": 0.55,
     "cover": "https://i.scdn.co/image/ab67616d0000b273e5b31ed2c549c7c7a2ed7081"},
    {"title": "Biking", "id": "5S4cCeafLRGrx8TqCVMZkR", "album": "Single", "valence": 0.48,
     "cover": "https://i.scdn.co/image/ab67616d0000b2732a929f57836b8e22d2afc1aa"},
    {"title": "Provider", "id": "6Pmpz5bOfVgRhnKQ1rJRa5", "album": "Single", "valence": 0.60,
     "cover": "https://i.scdn.co/image/ab67616d0000b27303dba28c13d746e2b5c9bfbd"},
    {"title": "Moon River", "id": "3CTWvaV1LYdVEW8hXvnxRl", "album": "Single", "valence": 0.25,
     "cover": "https://i.scdn.co/image/ab67616d0000b273d4c33bcef2700d760f51478c"},
    {"title": "In My Room", "id": "3WCXVzgj4JFTK1OIJULG5g", "album": "Single", "valence": 0.30,
     "cover": "https://i.scdn.co/image/ab67616d0000b27303dba28c13d746e2b5c9bfbd"},
    {"title": "DHL", "id": "5S2EYFNOgGXtvtFzlVVBbp", "album": "Single", "valence": 0.45,
     "cover": "https://i.scdn.co/image/ab67616d0000b27303dba28c13d746e2b5c9bfbd"},
    {"title": "Cayendo", "id": "0sf8Ac6mZ2B1HJIcJiqvbE", "album": "Single", "valence": 0.22,
     "cover": "https://i.scdn.co/image/ab67616d0000b27361d7d9e63e632f8f49eb6a91"},
    {"title": "Dear April", "id": "4oPdbFcBhJVyNsgJaAJnip", "album": "Single", "valence": 0.28,
     "cover": "https://i.scdn.co/image/ab67616d0000b2735e7680c1a6bce5b7ad8c8a6e"},
]
